import Mathlib.FieldTheory.AbsoluteGaloisGroup
import Mathlib.FieldTheory.Perfect
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.Algebra.Polynomial.Roots

/-!
# Frobenius as an element of the absolute Galois group of a finite field

`absoluteGaloisGroup (ZMod p)` is famously *infinite* (procyclic, topologically generated by
Frobenius, `≅ Ẑ`) — the natural contrasting example to `Field.absoluteGaloisGroup_real_card`
(finite, order `2`). This file proves it, in two stages:

1. Frobenius is a *nontrivial* element of `absoluteGaloisGroup (ZMod p)` (`frobAlgEquiv_ne_one`).
2. Frobenius has *infinite order* (`frobAlgEquiv_infinite_order`), by showing all of its powers
   `frobAlgEquiv p ^ n` (`n ≥ 1`) are nontrivial — the same argument as stage 1, applied to the
   iterated Frobenius `x ↦ x ^ (p ^ n)` and the polynomial `X ^ (p ^ n) - X`.

Grep-verified (2026-07-20): no `AlgEquiv`-over-`ZMod p` packaging of `frobeniusEquiv` and no
`Infinite (AlgebraicClosure ...)`-style result exist anywhere in mathlib4.
-/

open Polynomial

variable (p : ℕ) [Fact p.Prime]

/-- **Frobenius as an element of `absoluteGaloisGroup (ZMod p)`.** `frobeniusEquiv` (from
`Mathlib.FieldTheory.Perfect`, available since `AlgebraicClosure (ZMod p)` is a perfect field of
characteristic `p`) is a `RingEquiv`; this packages it as a `ZMod p`-algebra automorphism by
checking it fixes the prime field pointwise, via Fermat's little theorem (`ZMod.pow_card`) and
`algebraMap` commuting with `p`-th powers. Since
`Field.absoluteGaloisGroup K = AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K` definitionally,
`frobAlgEquiv p` *is* an element of `Field.absoluteGaloisGroup (ZMod p)`. -/
noncomputable def frobAlgEquiv :
    AlgebraicClosure (ZMod p) ≃ₐ[ZMod p] AlgebraicClosure (ZMod p) :=
  AlgEquiv.ofRingEquiv (f := frobeniusEquiv (AlgebraicClosure (ZMod p)) p) (by
    intro x
    rw [frobeniusEquiv_def, ← map_pow, ZMod.pow_card])

/-- `frobAlgEquiv p` acts the same way as `frobeniusEquiv`: raises to the `p`-th power. -/
theorem frobAlgEquiv_apply (x : AlgebraicClosure (ZMod p)) : frobAlgEquiv p x = x ^ p := by
  simp [frobAlgEquiv, frobenius_def]

/-- `X ^ m - X` is a nonzero polynomial whenever `2 ≤ m`: its `1`-coefficient is `-1`
(using `m ≠ 1`), not `0`. Used to bound its root set. -/
theorem X_pow_sub_X_ne_zero {m : ℕ} (hm : 2 ≤ m) :
    (X ^ m - X : (AlgebraicClosure (ZMod p))[X]) ≠ 0 := by
  have h1 : (X ^ m - X : (AlgebraicClosure (ZMod p))[X]).coeff 1 = -1 := by
    rw [coeff_sub, coeff_X_pow, if_neg (by omega : ¬ (1 : ℕ) = m), coeff_X_one]
    ring
  intro h
  rw [h] at h1
  simp at h1

/-- If some power `f` of Frobenius fixes every element of `AlgebraicClosure (ZMod p)`, then
`f = 1` in `AlgebraicClosure (ZMod p) ≃ₐ[ZMod p] AlgebraicClosure (ZMod p)`, contradicting `hf`
via `X ^ m - X`: every element being fixed means every element is a root of `X ^ m - X`, so
(since the field is infinite, being algebraically closed) that nonzero polynomial would have
infinitely many roots (`Polynomial.eq_zero_of_infinite_isRoot`), forcing it to be `0`. -/
private theorem false_of_pow_eq_id {m : ℕ} (hm : 2 ≤ m)
    (hall : ∀ x : AlgebraicClosure (ZMod p), x ^ m = x) : False := by
  have hroots : {x : AlgebraicClosure (ZMod p) |
      (X ^ m - X : (AlgebraicClosure (ZMod p))[X]).IsRoot x} = Set.univ := by
    ext x; simp [IsRoot, hall x]
  have hinf : Set.Infinite {x : AlgebraicClosure (ZMod p) |
      (X ^ m - X : (AlgebraicClosure (ZMod p))[X]).IsRoot x} := by
    rw [hroots]; exact Set.infinite_univ
  exact X_pow_sub_X_ne_zero p hm (Polynomial.eq_zero_of_infinite_isRoot _ hinf)

/-- **Frobenius is not the identity automorphism of `AlgebraicClosure (ZMod p)`** — the concrete
nontriviality fact this file is built around. Hence `frobAlgEquiv p` is a genuine, exhibited
nontrivial element of `Field.absoluteGaloisGroup (ZMod p)`. -/
theorem frobAlgEquiv_ne_one : frobAlgEquiv p ≠ 1 := by
  have hp2 : 2 ≤ p := (Fact.out : p.Prime).two_le
  intro h
  exact false_of_pow_eq_id p hp2 fun x => by
    have hx := DFunLike.congr_fun h x; simpa [frobAlgEquiv_apply] using hx

/-- The `n`-th power of `frobAlgEquiv p` (as a function) raises to the `p ^ n`-th power: the
`AlgEquiv` analogue of `iterateFrobeniusEquiv_def`, proved directly by induction since lifting
that mathlib lemma from `RingEquiv` to our `AlgEquiv` wrapper isn't needed. -/
theorem frobAlgEquiv_pow_apply (n : ℕ) (x : AlgebraicClosure (ZMod p)) :
    (frobAlgEquiv p ^ n) x = x ^ p ^ n := by
  induction n with
  | zero => simp
  | succ n ih =>
    have hstep : (frobAlgEquiv p ^ (n + 1)) x = frobAlgEquiv p ((frobAlgEquiv p ^ n) x) := by
      rw [pow_succ']; rfl
    rw [hstep, ih, frobAlgEquiv_apply, ← pow_mul, ← pow_succ]

/-- **No power of Frobenius (beyond `n = 0`) is the identity.** The same argument as
`frobAlgEquiv_ne_one`, applied to the iterated Frobenius `x ↦ x ^ (p ^ n)` and the polynomial
`X ^ (p ^ n) - X` (still nonzero, since `p ^ n ≥ p ≥ 2` for `n ≥ 1`). -/
theorem frobAlgEquiv_pow_ne_one {n : ℕ} (hn : 1 ≤ n) : frobAlgEquiv p ^ n ≠ 1 := by
  have hp2 : 2 ≤ p := (Fact.out : p.Prime).two_le
  have hpn : 2 ≤ p ^ n := calc
    2 ≤ p := hp2
    _ = p ^ 1 := (pow_one p).symm
    _ ≤ p ^ n := Nat.pow_le_pow_right (by omega) hn
  intro h
  exact false_of_pow_eq_id p hpn fun x => by
    have hx := DFunLike.congr_fun h x
    rw [← frobAlgEquiv_pow_apply p n x]; simpa using hx

/-- **Frobenius has infinite order in `Field.absoluteGaloisGroup (ZMod p)`.** Since
`frobAlgEquiv p ^ n ≠ 1` for every `n ≥ 1` (`frobAlgEquiv_pow_ne_one`), no positive power of
Frobenius is trivial, i.e. it is not of finite order. This is the key structural fact
underlying the classical description of `absoluteGaloisGroup (ZMod p)` as an infinite
(procyclic, `≅ Ẑ`) group generated by Frobenius. -/
theorem frobAlgEquiv_infinite_order : ¬ IsOfFinOrder (frobAlgEquiv p) := by
  rw [isOfFinOrder_iff_pow_eq_one]
  push Not
  exact fun n hn => frobAlgEquiv_pow_ne_one p hn

/-- **`Field.absoluteGaloisGroup (ZMod p)` is infinite** — the goal this whole file works
toward, packaged as a usable `Infinite` instance rather than left only as the `IsOfFinOrder`
fact above. In a finite group every element has finite order
(`isOfFinOrder_of_finite`); `frobAlgEquiv p` doesn't, so the group can't be finite.

The `show` at the start of the proof is load-bearing: `Field.absoluteGaloisGroup K` is a plain
`def` (not `abbrev`) for `AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K`, so typeclass search does
not automatically see through it to match a `Finite`/`Infinite` instance stated in terms of the
unfolded type (which is what `frobAlgEquiv p`'s stated type is, and what `isOfFinOrder_of_finite`
needs) — `show` bridges the two defeq-but-not-syntactically-equal expressions. -/
instance absoluteGaloisGroup_zmod_infinite : Infinite (Field.absoluteGaloisGroup (ZMod p)) := by
  show Infinite (AlgebraicClosure (ZMod p) ≃ₐ[ZMod p] AlgebraicClosure (ZMod p))
  by_contra hninf
  haveI hfin : Finite (AlgebraicClosure (ZMod p) ≃ₐ[ZMod p] AlgebraicClosure (ZMod p)) :=
    not_infinite_iff_finite.mp hninf
  exact frobAlgEquiv_infinite_order p (isOfFinOrder_of_finite (frobAlgEquiv p))
