import Mathlib.FieldTheory.AbsoluteGaloisGroup
import Mathlib.FieldTheory.Perfect
import Mathlib.FieldTheory.Finite.Basic
import Mathlib.Algebra.Polynomial.Roots

/-!
# Frobenius as an element of the absolute Galois group of a finite field

Milestone 1/2 of the finite-field case flagged as a "researched, not yet attempted" next step
in `IutLean.Anabelian.AbsoluteGaloisGroup`: `absoluteGaloisGroup (ZMod p)` is famously *infinite*
(procyclic, topologically generated by Frobenius, `≅ Ẑ`) — the natural contrasting example to
`Field.absoluteGaloisGroup_real_card` (finite, order `2`). Proving infiniteness outright is a
larger undertaking; this file lands the first concrete, self-contained piece: Frobenius really
is a *nontrivial* element of `absoluteGaloisGroup (ZMod p)`, not just an abstractly-bijective
`RingEquiv`. Milestone 2 (infinite order, hence `Infinite (absoluteGaloisGroup (ZMod p))`) is
left for a future step.

Grep-verified (2026-07-20): no `AlgEquiv`-over-`ZMod p` packaging of `frobeniusEquiv` and no
`Infinite (AlgebraicClosure ...)`-style result exist anywhere in mathlib4.
-/

open Polynomial

variable (p : ℕ) [Fact p.Prime]

/-- **Frobenius as an element of `absoluteGaloisGroup (ZMod p)`.** `frobeniusEquiv` (from
`Mathlib.FieldTheory.Perfect`, available since `AlgebraicClosure (ZMod p)` is a perfect field of
characteristic `p`) is a `RingEquiv`; this packages it as a `ZMod p`-algebra automorphism by
checking it fixes the prime field pointwise, via Fermat's little theorem (`ZMod.pow_card`) and
`algebraMap` commuting with `p`-th powers. Since
`Field.absoluteGaloisGroup K = AlgebraicClosure K ≃ₐ[K] AlgebraicClosure K` definitionally,
`frobAlgEquiv p` *is* an element of `Field.absoluteGaloisGroup (ZMod p)`. -/
noncomputable def frobAlgEquiv :
    AlgebraicClosure (ZMod p) ≃ₐ[ZMod p] AlgebraicClosure (ZMod p) :=
  AlgEquiv.ofRingEquiv (f := frobeniusEquiv (AlgebraicClosure (ZMod p)) p) (by
    intro x
    rw [frobeniusEquiv_def, ← map_pow, ZMod.pow_card])

/-- `X ^ p - X` is a nonzero polynomial: its `1`-coefficient is `-1` (using `p ≠ 1`, since `p`
is prime), not `0`. Used to bound its root set. -/
theorem X_pow_sub_X_ne_zero :
    (X ^ p - X : (AlgebraicClosure (ZMod p))[X]) ≠ 0 := by
  have hp2 : 2 ≤ p := (Fact.out : p.Prime).two_le
  have h1 : (X ^ p - X : (AlgebraicClosure (ZMod p))[X]).coeff 1 = -1 := by
    rw [coeff_sub, coeff_X_pow, if_neg (by omega : ¬ (1 : ℕ) = p), coeff_X_one]
    ring
  intro h
  rw [h] at h1
  simp at h1

/-- **Frobenius is not the identity automorphism of `AlgebraicClosure (ZMod p)`** — the concrete
nontriviality fact this file is built around. If `frobAlgEquiv p = 1`, every element `x` would
satisfy `x ^ p = x`, i.e. every element of the (infinite, since algebraically closed) field
`AlgebraicClosure (ZMod p)` would be a root of `X ^ p - X`. But a nonzero polynomial has only
finitely many roots (`Polynomial.eq_zero_of_infinite_isRoot`), contradicting
`X_pow_sub_X_ne_zero`. Hence `frobAlgEquiv p` is a genuine, exhibited nontrivial element of
`Field.absoluteGaloisGroup (ZMod p)`. -/
theorem frobAlgEquiv_ne_one : frobAlgEquiv p ≠ 1 := by
  intro h
  have hall : ∀ x : AlgebraicClosure (ZMod p), x ^ p = x := by
    intro x
    have hx := DFunLike.congr_fun h x
    simpa [frobAlgEquiv, frobeniusEquiv_def, frobenius_def] using hx
  have hroots : {x : AlgebraicClosure (ZMod p) |
      (X ^ p - X : (AlgebraicClosure (ZMod p))[X]).IsRoot x} = Set.univ := by
    ext x
    simp [IsRoot, hall x]
  have hinf : Set.Infinite {x : AlgebraicClosure (ZMod p) |
      (X ^ p - X : (AlgebraicClosure (ZMod p))[X]).IsRoot x} := by
    rw [hroots]; exact Set.infinite_univ
  exact X_pow_sub_X_ne_zero p (Polynomial.eq_zero_of_infinite_isRoot _ hinf)
